'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import NavigationBar from './components/nav-bar/Nav-bar';
import { Layout } from 'antd';
import { SessionProvider } from 'next-auth/react';
import { ModeContextProvider } from './context/ModeContext';

const { Content, Footer } = Layout;

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const footerStyle = {
  textAlign: 'center',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ModeContextProvider>
            <Layout>
              <NavigationBar />
              {children}
              <Footer style={footerStyle}>footer</Footer>
            </Layout>
          </ModeContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
