"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "./components/nav-bar/Nav-bar";
import { Layout } from "antd";
const { Content, Footer } = Layout;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const contentStyle = { height: "100vh", padding: "24px" };
const footerStyle = {
  textAlign: "center",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout>
          <NavigationBar />
          <Content style={contentStyle}>{children}</Content>
          <Footer style={footerStyle}>footer</Footer>
        </Layout>
      </body>
    </html>
  );
}
